# Generated by Django 4.2.3 on 2023-07-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0003_song_album_song_preview_url_song_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='name',
            field=models.CharField(default='lowell', max_length=100),
        ),
    ]
